# Generated by Django 4.2.6 on 2023-10-11 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Barber', '0003_remove_customer_cus_name_remove_customer_reviews_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(default='Lastname', max_length=50),
        ),
    ]
