# Generated by Django 4.2.6 on 2023-10-11 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Barber', '0004_remove_customer_address_alter_customer_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barber',
            name='barber_name',
            field=models.CharField(max_length=30),
        ),
    ]
