# Generated by Django 4.2.6 on 2023-10-11 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Barber', '0005_alter_barber_barber_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='barber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Barber.barber'),
        ),
    ]
