# Generated by Django 4.2.6 on 2023-10-11 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Barber', '0006_review_barber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='barber',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Barber.barber'),
        ),
    ]
