# Generated by Django 4.2.6 on 2023-10-25 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Barber', '0006_alter_user_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_num',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='images/PIC_0102.JPG', upload_to='uploads/'),
        ),
    ]
