# Generated by Django 4.2.6 on 2023-10-25 19:47

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Barber', '0008_user_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='profileView', editable=False, populate_from=['username', 'id']),
        ),
    ]
