# Generated by Django 4.2.6 on 2023-10-11 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Barber', '0010_review_review_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='last_name',
        ),
        migrations.AddField(
            model_name='customer',
            name='username',
            field=models.CharField(default='Username', max_length=50),
        ),
    ]
