# Generated by Django 4.2.6 on 2023-10-16 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Barber', '0011_remove_customer_first_name_remove_customer_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='barber',
        ),
        migrations.RemoveField(
            model_name='review',
            name='customer',
        ),
        migrations.AddField(
            model_name='customer',
            name='first_name',
            field=models.CharField(default='Firstname', max_length=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_name',
            field=models.CharField(default='Lastname', max_length=50),
        ),
    ]
