# Generated by Django 4.2.6 on 2023-10-16 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Barber', '0012_remove_review_barber_remove_review_customer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affiliation_code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=60, unique=True)),
                ('phone_num', models.CharField(blank=True, max_length=12, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='barber',
            name='barber_name',
        ),
        migrations.RemoveField(
            model_name='barber',
            name='reviews',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='barber',
            name='email',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='barber',
            name='f_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='barber',
            name='is_owner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='barber',
            name='l_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='barber',
            name='password',
            field=models.CharField(default='Password', max_length=30, unique=True),
        ),
        migrations.AddField(
            model_name='barber',
            name='phone_num',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='barber',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='barber',
            name='username',
            field=models.CharField(default='Username', max_length=30, unique=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='barber',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Barber.barber'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='f_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='l_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(default='Password', max_length=30, unique=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='username',
            field=models.CharField(default='Username', max_length=30, unique=True),
        ),
    ]
