# Generated by Django 4.2.6 on 2023-10-16 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Barber', '0013_shop_remove_barber_barber_name_remove_barber_reviews_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
