# Generated by Django 4.2.6 on 2023-11-13 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Barber', '0016_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5),
        ),
    ]
