# Generated by Django 4.2.6 on 2023-10-23 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Barber', '0017_user_remove_barberuser_groups_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CusUser',
            new_name='Customer',
        ),
    ]
