# Generated by Django 4.2.6 on 2023-11-13 21:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Barber", "0018_timeslot_appointment"),
    ]

    operations = [
        migrations.AddField(
            model_name="barber",
            name="work_end_time",
            field=models.TimeField(default=datetime.time(17, 0)),
        ),
        migrations.AddField(
            model_name="barber",
            name="work_start_time",
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
    ]
