# Generated by Django 4.2.6 on 2023-11-15 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Barber", "0019_barber_work_end_time_barber_work_start_time"),
        ("Barber", "0020_owner_user_is_owner_shop"),
    ]

    operations = []
