# Generated by Django 4.2.6 on 2023-11-20 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Barber", "0021_merge_20231115_1044"),
        ("Barber", "0021_merge_20231115_1056"),
    ]

    operations = []
