# Generated by Django 4.2.6 on 2023-11-20 03:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Barber', '0021_owner_user_is_owner_shop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='barbers',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='slug',
        ),
        migrations.AddField(
            model_name='shop',
            name='affiliation_code',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_shops', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='slug',
            field=models.SlugField(auto_created=True, unique=True),
        ),
    ]
