# Generated by Django 4.2.7 on 2023-11-21 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Barber", "0022_merge_20231120_2047"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="barber",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="services",
                to="Barber.barber",
            ),
        ),
    ]
