# Generated by Django 4.2.6 on 2023-11-20 20:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Barber", "0022_merge_20231119_1750"),
    ]

    operations = [
        migrations.AddField(
            model_name="timeslot",
            name="booked_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="booked_appointments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
