# Generated by Django 4.2.7 on 2023-11-22 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Barber", "0023_alter_service_barber"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="barber",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="services",
                to="Barber.barber",
            ),
        ),
    ]
