# Generated by Django 4.2.6 on 2023-11-24 22:46

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Barber', '0023_alter_shop_email_alter_shop_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='barber',
            name='affiliation_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='barbers',
            field=models.ManyToManyField(blank=True, related_name='shops', to='Barber.barber'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_shops', to='Barber.owner'),
        ),
        migrations.AlterField(
            model_name='user',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='username', unique=True),
        ),
    ]
