# Generated by Django 4.2.6 on 2023-11-24 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Barber', '0025_shop_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='slug',
        ),
    ]
