# Generated by Django 4.2.6 on 2023-11-24 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Barber', '0026_remove_shop_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
