# Generated by Django 4.2.6 on 2023-11-25 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Barber', '0023_timeslot_booked_by'),
        ('Barber', '0024_alter_service_barber'),
        ('Barber', '0027_shop_slug'),
    ]

    operations = [
    ]
