# Generated by Django 4.2.6 on 2023-11-27 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Barber", "0030_timeslot_booked_by_alter_shop_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_pic",
            field=models.ImageField(
                default="images/customer.JPG", upload_to="uploads/"
            ),
        ),
    ]
